### ISSUE TITLE
Weapon Trinkets ?

### ISSUE THREAD

**Issue by niebaum20** [FromDarkHell/BL3ProfileEditor#1]
Hey man, great work with the Profile Editor but I have a question, I got all the missing Heads, Skins and Echo Themes but it doesn't work with Weapon Trinkets ? I'm missing 2 from those timed events, Bloody Harvest and Broken Hearts. Is it possible to make the Editor unlock Weapon Trinkets as well ?

**Comment by FromDarkHell** [comment]
Weapon Trinkets / Weapon Skins are stored on the save games, if you want to edit your saves to have 'em all use [apocalyptech's save editor](https://github.com/apocalyptech/bl3-cli-saveedit), if it doesn't have it, send in an issue over yonder

**Comment by FromDarkHell** [comment]
As it turns out, I'm just an idiot but weapon trinkets are (apparently) stored on the profile, but they seem to be stored in an odd way compared to the other customizations
