### ISSUE TITLE
Not unlock all the heads for Amara

### ISSUE THREAD

**Issue by matrix7625** [FromDarkHell/BL3ProfileEditor#10]
I used this for unlock Cosmetics, heads and these things, but, in Amara this show 43/44  in Moze and others unlocked all but not in Amara.

**Comment by FromDarkHell** [comment]
This is known and intended; In DLC5 there are duplicates of the "final form" heads. There are no differences between the two.
So you can either have a "fully" unlocked head count, or have a double entry list.

Cosmetics are generated using apocalyptech's [Customization List](https://docs.google.com/spreadsheets/d/1v-F_3C2ceaFKJae1b6wmbelw_jLjmPPriBLzGTZMqRc/)
