### ISSUE TITLE
Missing file when I downloaded the sln

### ISSUE THREAD

**Issue by MauroMS** [FromDarkHell/BL3ProfileEditor#3]
Hey @FromDarkHell great job with the editor! I was trying to look at the code and see if I can find a way to create something to fiddle with locations (due to that trophy bugged).

Bug I got this error when I try to run the solution on my machine
![image](https://user-images.githubusercontent.com/12518255/80922266-d1de8c80-8d73-11ea-983a-2f1e6ce91b5a.png)
It looks like this file is used on Editor.xaml.cs

Can I just comment that or it's something useful?

Thanks!

**Comment by FromDarkHell** [comment]
Its used for the debug menu, seems to be an issue with the git ignore whoops (also what's the `trophy bugged`?), can comment it out if you want

**Comment by MauroMS** [comment]
> Its used for the debug menu, seems to be an issue with the git ignore whoops (also what's the `trophy bugged`?), can comment it out if you want

Thanks for the quick reply!
There is a bug if you play co-op the game does not save correctly the locations you visited, so it makes impossible to get the "All locations visited" trophy with that char, so you need to create a new one and play again on single player mode to get that trophy.
