### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pablo-Plus** [FromDarkHell/BL3ProfileEditor#4]
![Anotación 2020-05-06 212604](https://user-images.githubusercontent.com/64936248/81241279-39007900-8fe0-11ea-8794-d93cf4a4d12d.jpg)
Hi. All my profiles archives show the same message.
But i can edit them in new bordelands online editor without probelms, and off course play them.
(Sorry my english)

**Comment by FromDarkHell** [comment]
You're not editing a profile.
You're editing a save file.
A profile file is normally titled `profile.sav`.
