### ISSUE TITLE
Golden keys don't save

### ISSUE THREAD

**Issue by punkhop** [FromDarkHell/BL3ProfileEditor#6]
Huge fan of this profile editor. THANK YOU.

I just got the new release. I click + to add a golden key, and save. Close the program, reopen, and golden keys are back to 0/empty. Any ideas?

**Comment by punkhop** [comment]
Correction: no new data will save. I increased grenade damage a few points, saved, reopened, it's back to where it started. I tried running as administrator, same thing,

**Comment by FromDarkHell** [comment]
Try uploading your profile here (as well as a log from the debug console (wrench in the top right) (open the console and then open your file) ), seems fine and working to me

**Comment by punkhop** [comment]
Attached!

Debug console:
`Reading new file: "C:\Users\Peet\Documents\My Games\Borderlands 3\Saved\SaveGames\e12c08746e45479792ad3530d139701e\profile.sav"
Header: GVAS
Save Game Version: 2
Package version: 516
Engine version: 4.20.3.2149689425
Build ID: OAK-PATCHDIESEL1-137
Custom Format Version: 3
Custom Format Data Count: 59
Save Game Type: BP_DefaultOakProfile_C
Length of data: 159903
Initialized CRC32 hashes of trinkets/weapons/keys...
Rank Data (Accuracy): 25
Rank Data (Action Skill Cooldown): 20
Rank Data (Critical Damage): 20
Rank Data (FFYL Duration): 60
Rank Data (FFYL Move Speed): 17
Rank Data (Grenade Damage): 20
Rank Data (Gun Damage): 24
Rank Data (Gun Fire Rate): 17
Rank Data (Max Health): 15
Rank Data (Melee Damage): 10
Rank Data (Luck): 400
Rank Data (Recoil Reduction): 45
Rank Data (Reload Speed): 16
Rank Data (Shield Capacity): 12
Rank Data (Shield Rechage Delay): 18
Rank Data (Shield Recharge Rate): 16
Rank Data (Vehicle Damage): 16
Rank Data (Elemental Damage): 21
Injecting GR into saves...
Reading file "C:\Users\Peet\Documents\My Games\Borderlands 3\Saved\SaveGames\e12c08746e45479792ad3530d139701e\1.sav"
Header: GVAS
Save Game Version: 2
Package version: 516
Engine version: 4.20.3.2149689425
Build ID: OAK-PATCHDIESEL1-137
Custom Format Version: 3
Custom Format Data Count: 59
Save Game Type: OakSaveGame
Length of data: 1487649
Parsing save: Zane
Reading file "C:\Users\Peet\Documents\My Games\Borderlands 3\Saved\SaveGames\e12c08746e45479792ad3530d139701e\profile.sav"
Header: GVAS
Save Game Version: 2
Package version: 516
Engine version: 4.20.3.2149689425
Build ID: OAK-PATCHDIESEL1-137
Custom Format Version: 3
Custom Format Data Count: 59
Save Game Type: BP_DefaultOakProfile_C
File "C:\Users\Peet\Documents\My Games\Borderlands 3\Saved\SaveGames\e12c08746e45479792ad3530d139701e\profile.sav" is not a save.
Done injecting GR into saves




[profile.zip](https://github.com/FromDarkHell/BL3ProfileEditor/files/4774034/profile.zip)

**Comment by FromDarkHell** [comment]
It seems in my hot mess of a transition to .NET Core 3.1, my binding setup for the guardian rank broke (and I just forgot a basic check for the golden key error :P), if you want to modify it right now, you can just use [v1.0.4](https://github.com/FromDarkHell/BL3ProfileEditor/releases/tag/v1.0.4) until I bother/figure out how to fix it
