### ISSUE TITLE
Not a bl3 profile.

### ISSUE THREAD

**Issue by Badonkadonk3** [FromDarkHell/BL3ProfileEditor#7]
so whenever i try to open the profile.sav its says its not a bl3 file. I have the latest editor and bl3.

**Comment by FromDarkHell** [comment]
Upload your profile.sav, and take a screenshot of the console (Wrench Icon in the top right) after opening a save (you need to open console then open save) and put it in this issue

**Comment by badlvck** [comment]
![not a profile](https://user-images.githubusercontent.com/67699355/86258129-b2978c00-bb77-11ea-9581-1e99eabc85a5.PNG)

I am also having the same issue.

**Comment by badlvck** [comment]
![Not a profile](https://user-images.githubusercontent.com/67699355/86258296-e672b180-bb77-11ea-865c-4e1de987562a.jpg)
Also having the same issue

**Comment by bWildcard** [comment]
Having similar issue
Running .exe
Open 1.sav

"File Error"
"Loaded file is not a profile"

Debug Con
Reading new file: "C:\Users\PC\Documents\My Games\Borderlands 3\Saved\SaveGames\76561198015947447\1.sav"
Header: GVAS
Save Game Version: 2
Package version: 516
Engine version: 4.20.3.2149751297
Build ID: OAK-PATCHWIN641-118
Custom Format Version: 3
Custom Format Data Count: 59
Save Game Type: OakSaveGame
Length of data: 1445631
Loaded file is not a profile...

**Comment by FromDarkHell** [comment]
That's because you're loading a save file. If you want to edit a character's gear then use [Baysix's Save Editor](https://www.bl3editor.com/)

if you're trying to actually edit your profile data read the [README](https://github.com/FromDarkHell/BL3ProfileEditor#installation)
